spring:
  application:
    name: bank-service
  datasource:
    driverClassName: org.postgresql.Driver
    initialization-mode: always
    password: ${PASS}
    platform: postgres
    url: jdbc:postgresql://localhost:5432/bank_service
    username: postgres
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: false
jwt:
  secret: security

server:
  port: 8080
#  ssl:
#    key-store: classpath:local-ssl.p12
#    key-store-password: password
#    keyStoreType: PKCS12
#    keyAlias: local_ssl

eureka:
  client:
    service-url:
      default-zone: http://eureka:password@localhost:8761/eureka

bank1-application:
  backend: http://192.168.238.103:8090/bank1

bank2-application:
  backend: http://192.168.238.103:8099/bank2

psp:
  frontend: http://192.168.238.103:4200
  error-payment: /bank-cancel
  success-payment: /bank-success
  failed-payment: /bank-failed
  auth-service: http://localhost:8083/web-shop-url/

bank:
  access-token: /api-keys/generate

