spring:
  application:
    name: paypal-service
  datasource:
    driverClassName: org.postgresql.Driver
    initialization-mode: always
    password: ${PASS}
    platform: postgres
    url: jdbc:postgresql://localhost:5432/paypal
    username: postgres
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: false
jwt:
  secret: security

paypal:
  mode: sandbox
  client:
    id: Afx4OhlhN1lj1-8-w-OVVYKzIBJwqSqzNIzd3PRDTH6YkEebvb4TOBiwL_tp3NN4DzJcf0ABMCvcZ4Qp
    secret: EIk6cnDJiPCgEiLrh9Wy5WaJUQMU4XIIiPFBG6k1UVcgpaNDNdbBQcH7XXFFr3QWKuzdX-BEOJulNv8O

server:
  port: 8084

eureka:
  client:
    service-url:
      default-zone: http://eureka:password@localhost:8761/eureka

psp:
  url: 'http://localhost:4200/'
  subscription_cancel_url: 'http://localhost:4200/cancel-subscription'
  subscription_confirm_rul: 'http://localhost:4200/confirm-subscription'


